---
- name: create aws organization account using awscli
  shell: aws organizations create-account --email "aws2020+{{ env_name}}@{{ email_domain }}" --account-name "{{ env_name }}" --role-name "{{ iam_role }}" --output json --region "{{ aws_region_exec }}"